FROM ubuntu 
MAINTAINER dohungcuongdev1295@gmail.com
CMD ["echo" , "hello world"]
ENTRYPOINT ["echo"]

#Build image
#   docker build -t ici .

#Build container
#   docker run ici

#Build  container
#   docker run ici hello